name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        go: ["1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: ggerganov/whisper.cpp
          ref: v1.3.0
          path: libwhisper
      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: ${{ matrix.go }}
      - run: |
          cd libwhisper/bindings/go
          make libwhisper
      # we don't have any tests yet
      # - run: "go test ./..."
      #  env:
      #    C_INCLUDE_PATH: ${{ github.workspace }}/whisper
      #    LIBRRARY_PATH: ${{ github.workspace }}/whisper
      - run: "echo $C_INCLUDE_PATH && ls $C_INCLUDE_PATH"
        env:
          C_INCLUDE_PATH: ${{ github.workspace }}/libwhisper
          LIBRRARY_PATH: ${{ github.workspace }}/libwhisper
      - run: "make lint LIBWHISPER=${{ github.workspace }}/libwhisper"
