name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
        go: ["1.20.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: ggerganov/whisper.cpp
          ref: v1.3.0
          path: whisper
      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: ${{ matrix.go }}
      - run: |
          cd whisper/bindings/go
          make whisper
      # we don't have any tests yet
      # - run: "go test ./..."
      #  env:
      #    C_INCLUDE_PATH: "/whisper"
      #    LIBRRARY_PATH: "/whisper"
      - run: "go vet ./..."
        env:
          C_INCLUDE_PATH: "${GITHUB_WORKSPACE}/whisper"
          LIBRRARY_PATH: "${GITHUB_WORKSPACE}/whisper"
      - run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
        env:
          C_INCLUDE_PATH: "${GITHUB_WORKSPACE}/whisper"
          LIBRRARY_PATH: "${GITHUB_WORKSPACE}/whisper"
